{
	"version": 1479375790,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/platformdrop-sheet0.png",
		"images/player-sheet0.png",
		"images/goleft-sheet0.png",
		"images/jump-sheet0.png",
		"images/slippery-sheet0.png",
		"images/crystal-sheet0.png",
		"images/crystalobsatacle-sheet0.png",
		"images/crystal2-sheet0.png",
		"images/crystal3-sheet0.png",
		"images/platformsidetoside-sheet0.png",
		"images/platform2-sheet0.png",
		"images/platform-sheet0.png",
		"images/fallingcrystal-sheet0.png",
		"images/fallingcrystalcolission-sheet0.png",
		"images/stopper-sheet0.png",
		"images/checkpoint-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/helpbox-sheet0.png",
		"images/helpbox2-sheet0.png",
		"images/helpbutton-sheet0.png",
		"images/helpbox3-sheet0.png",
		"images/background-sheet0.png",
		"images/firstcrystal-sheet0.png",
		"images/floorandwalls-sheet0.png",
		"images/sprite5-sheet0.png",
		"media/background music.m4a",
		"media/background music.ogg",
		"media/checkpoint.m4a",
		"media/checkpoint.ogg",
		"media/falling crystal.m4a",
		"media/falling crystal.ogg",
		"media/falling platform.m4a",
		"media/falling platform.ogg",
		"media/jump.m4a",
		"media/jump.ogg",
		"media/shatter crystal.m4a",
		"media/shatter crystal.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}